import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from '../components/header'
import Footer from '../components/footer'
import Container from '../components/container'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Posts",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={`flex flex-col text-zinc-600 ${inter.className}`}>
      <Container>
        <Header />
          {children}
        <Footer />
      </Container>
      </body>
      </html>
  );
}
